### ISSUE TITLE
v1.18.0?

### ISSUE THREAD

**Issue by Wallong** [googlesamples/arcore-depth-lab#1]
I am excited about these samples, but v1.18.0 is still not available for us until now. So when will it be published?

**Comment by andersemil** [comment]
🤥

**Comment by kidavid** [comment]
Thanks for your interest in Depth Lab!

ARCore SDK v1.18.0 and updated documentation will be rolled out in the next couple of hours. Please check back at around 12PM PDT (Los Angeles time) for ARCore SDK v1.18.0. The documentation will follow at around 4PM.

**Comment by ruofeidu** [comment]
ARCore SDK v1.18.0 is now open to public: https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.18.0

Please follow the instructions in our `README.md` file to build the project. Let us know if you encounter any issues.
