### ISSUE TITLE
S20 Ultra - InvalidOperationException("Invalid depth value");

### ISSUE THREAD

**Issue by sethhaller** [googlesamples/arcore-depth-lab#10]
When testing on S20 Ultra is throwing InvalidOperationException("Invalid depth value");
Objects and wraps are not being pinned and are just floating around when moving phone.
I did not encounter this issues when testing on a S9+.
Also S20 Ultra has no issue when running Depth Lab app.

**Comment by sethhaller** [comment]
Seems to have been just a one time issue?

**Comment by ruofeidu** [comment]
Hi sethhaller,

Thank you for your feedback in Depth Lab?
How did you resolve this issue? Did you fix it by restarting the phone?

Thank you so much! 

Cheers,
Ruofei

**Comment by sethhaller** [comment]
Ruofei,

I rebuilt and redeployed the App and the issue did not reappear.

Thanks,
Seth
