### ISSUE TITLE
MaterialWrap and ScreenSpaceDepthMesh issue on Samsung S20+

### ISSUE THREAD

**Issue by scuube** [googlesamples/arcore-depth-lab#11]
Hi there,

I have a small issue regarding the MaterialWrap and ScreenSpaceDepthMesh scenes of the Depth Lab.
Instead of getting a sculpted mesh that corresponds with the colored depth map of the DepthEffects scene,  I get a flat, oval shaped mesh (see image below). This happens with the MaterialWrap scene, and also with the ScreenSpaceDepthMesh scene when I press 'freeze'.

![Screenshot_20200705-224526_Depth Lab - All](https://user-images.githubusercontent.com/67877438/86542009-0f959800-bf12-11ea-9983-dea3d8d14bab.jpg)

The issue happens on both the play store version of the app, as well as the version I built in Unity. I have a Samsung Galaxy S20 plus with a seemingly working ToF sensor in other scenes.

Is there a fix for this issue?

Thanks, Nick

**Comment by ruofeidu** [comment]
Hi scuube,

Thank you for your interests in DepthLab. Would you like to confirm that other scenes work properly and would you like to give it another try after a restart? Thank you so much!

Cheers,
Ruofei

**Comment by scuube** [comment]
Hi Ruofei,

Thank you for the quick reply, I can confirm other scenes work properly. Even after uninstalling the app, rebooting android and reinstalling the app, the problem still occurs.

(Also, the app runs a bit choppy (framerate I estimate between 30fps and dips to 10fps regularly), even when no geometry is placed. This is also the case for the helloar app, which runs smoother on my Samsung Galaxy A8 (2018) with the same apk file. Atom Visualizer for Arcore runs very smooth on my s20+ in comparison. Please tell me if this should have it's own thread)

Cheers,
scuube

**Comment by ruofeidu** [comment]
Would you like to try using Unity 2018.4.x to build the app? Thank you so much!

Cheers,
Ruofei

**Comment by ruofeidu** [comment]
We have just released an update: https://github.com/googlesamples/arcore-depth-lab/releases/tag/1.1.0 Let us know if you still have issues.
