### ISSUE TITLE
Camera Choppiness/Jittering 

### ISSUE THREAD

**Issue by sethhaller** [googlesamples/arcore-depth-lab#12]
When running the Depth API there is a very noticeable choppiness/jittering - https://youtu.be/1KoE8fglirM
When running the Depth Lab App from Play Store everything is very smooth - https://youtu.be/iRogGT21ke8
I tested this on a S9+ and S20 Ultra and had same issue.
I believe the camera is, for some reason, is at a very low FPS.
I checked the FPS settings and camera settings within the Depth API and everything appeared correct.
Not sure what is causing this.

**Comment by ruofeidu** [comment]
Hi Seth,

It looks to me like low FPS of the camera. Would you like to confirm that this issue can be reproduced by restarting your phone? And the APK is NOT built with `development build` checkbox on. Which Unity version did you use by the way? Thank you so much! 

Cheers,
Ruofei

**Comment by sethhaller** [comment]
Ruofei,

The issue remains after restarting the phone.
Is not a development build.
Using Unity 2020.0b13.
Believe the FPS should be set correctly by:
fileName = "ARCoreCameraConfigFilter",
menuName = "Google ARCore/CameraConfigFilter",

Thanks,
Seth

**Comment by ruofeidu** [comment]
Hi Seth,

Sorry that I cannot replicate your issue. Would you like to try using Unity 2018.4 and see if the jitter has gone?

Thank you so much!

**Comment by sethhaller** [comment]
Ruofei,

Tried again in Unit 2018.4 and everything is smooth (no jitters), thanks!

Seth
