### ISSUE TITLE
BUG: Occlusions is not working properly into HelloAR using Depth API on android app

### ISSUE THREAD

**Issue by Holotwin** [googlesamples/arcore-depth-lab#15]
Hello, I am using:
Unity 2018.4.22 for windows 2010
Arcore arcore-unity-sdk-1.18.0
Huawei p30 pro (Depth API supported)

I pasted the folder **arcore-depth-lab-master** including the project settings to the new unity project. 
I could build the **Depth Lab apk** and running on my phone without a problem.

But when I try to build the **HelloAR** example enabling Depth API.

The occlusion does not work properly as **Depth Lab** app built from unity and run from the same phone.

![image](https://user-images.githubusercontent.com/68569657/88018563-9c814980-caed-11ea-8179-973174cd7928.png)
![Screenshot_20200721_005922_com google ar unity arcore_depth_lab 1](https://user-images.githubusercontent.com/68569657/88018872-2df0bb80-caee-11ea-919d-f16f9b24fe8a.jpg)
![Screenshot_20200721_005922_com google ar unity arcore_depth_lab](https://user-images.githubusercontent.com/68569657/88018880-30531580-caee-11ea-8334-221adb865357.jpg)
![Screenshot_20200721_010202_com google ar unity arcore_depth_lab](https://user-images.githubusercontent.com/68569657/88018885-31844280-caee-11ea-982c-05e32013afd7.jpg)

Sometimes it gets dark as a shadow or gets the color of the object. But I think it has to disappear the object´s body when a physical object is between it and camera as Avatar depth lab
Any solution of this?

**Comment by ruofeidu** [comment]
Hi Holotwin,

HelloDepth is a subproject in https://github.com/google-ar/arcore-unity-sdk, which is out of the scope of Depth Lab. Would you please route this question to ARCore Unity SDK team? Thank you so much! 

Cheers,
Ruofei
