### ISSUE TITLE
device should be compatible

### ISSUE THREAD

**Issue by ARPatrick** [googlesamples/arcore-depth-lab#16]
Hi,

I setup the DepthLab Project as described on my Samsung S8 (which should be compatible). In fact i ran a Sample that used the ARCore Depth feature thru ARFoundation and it worked fine. However in the DepthLab project the app compiles but states that my device is incompatible and does not receive a cameraimage (background is black).
I ran this on Unity 2019.4.4f1 with the XR Legacy Input Helpers and Multiplayer HLAPI packages. I did not change anything other than adding those packages and switching to android as a plattform.
Any Ideas on what is going wrong?

Thanks for your hard Work
ARPatrick

**Comment by ruofeidu** [comment]
Hey ARPatrick,

Would you like to try Unity 2018.4.24f1 and ARCore SDK for Unity v1.18.0 as README.md instructed? Sorry that for compatibility to lower versions of Unity and ARCore, some of the APIs used in this sample needs updating manually. Please let me know if lower version of Unity works or not! 

Cheers,
Ruofei

**Comment by ARPatrick** [comment]
I ran the sample on Unity 2018.22f1 (this is the version the project was recognized as) and ARCore v1.18.0. This worked without troubles.
I would like to run it in newer Unity versions as well though. I suspect that it might have something to do with 2019.4.4f1 deciding that the target API would be API level 29 (Android 10) which is not supported by the S8 anymore. I might be totally wrong. 
Thanks for the awesome sample projects.

**Comment by ruofeidu** [comment]
Hi ARPatrick,

Thank you again for your interests and experiments with Depth Lab.

As ARCore is currently compatible with Unity 2018.4.x, we need to ensure Depth Lab is compatible with old versions of Unity projects. Sorry for the inconvenience for you when upgrading the Unity versions. I haven't got time to try in latest Unity on different Android devices (I don't have an S8 for example...) but would like to know the solution if you finally resolved it :) 

Cheers,
Ruofei
