### ISSUE TITLE
ScreenSpaceDepthMesh example broken?

### ISSUE THREAD

**Issue by dzak83** [googlesamples/arcore-depth-lab#18]
Hi,
I am trying ScreenSpaceDepthMesh examplese but nothing happens. I loaded ScreenSpaceDepthMesh and StereoPhoto scenes.

Is it expected? What do I miss?

**Comment by ruofeidu** [comment]
Sorry for the late reply. ScreenSpaceDepthMesh should show real-time depth mesh and stereo photo should show the 3D photo effect. Which Unity and phone were you using?

**Comment by dzak83** [comment]
I am using Pixel 2 XL. I don't remember which Unity version I used for that sample. I would assume the one suggested.

**Comment by ruofeidu** [comment]
We just released new source code: https://github.com/googlesamples/arcore-depth-lab/releases and Play Store app: https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab. Let me know if this issue persists.

**Comment by dzak83** [comment]
Thanks. I didn't check the source code yet but app from the store seems to be working now on Pixel 2 XL.

**Comment by ruofeidu** [comment]
Great news! Thanks for checking!

**Comment by Dorixed** [comment]
Hi Ruofei,
I am using Unity 2019.4.36 to build this project and met the same problem. Other scenes like depth map or collider work fine, but nothing happens in the Mesh. However, when I use the released app in Google Play, the mesh works fine too. I am wondering if some specific modifications are needed to use this scene. Looking forward to your reply!
