### ISSUE TITLE
Redmi Note 8 Pro - not supported?

### ISSUE THREAD

**Issue by nnseva** [googlesamples/arcore-depth-lab#2]
The Google Play doesn't allow to install the application to the Redmi Note 8 Pro because of incompatibility.

Are you sure?

**Comment by kidavid** [comment]
Please find the list of ARCore compatible devices with Depth API support here: https://developers.google.com/ar/discover/supported-devices

Please look for "Supports Depth API" in the **Notes** column of each listed device.
