### ISSUE TITLE
Implemetation of ARCore Depth API functions in AR Foundation 4.x.x?

### ISSUE THREAD

**Issue by RamoramaInteractive** [googlesamples/arcore-depth-lab#20]
I want to implement some depth functions of the ARCore Depth API into an already existing AR Foundation project.
Is it possible to copy the scripts and adapt the gradle settings?

I want to improve the functionalities to toss a dice on a ground with occlusions. You should be able to cover objects with your hand or a person.

**Comment by ruofeidu** [comment]
I played with latest AR Foundation last month and it supports Depth API. You may have to tweak the depth input APIs in DepthSource.cs to get the correct input of Depth. The core idea is: DepthLab only needs depth map, intrinsic and extrinsic matrices of the camera, and RGB image to work with.  See https://augmentedperception.github.io/depthlab/ for more detail.

**Comment by RamoramaInteractive** [comment]
How can I tweak the depth input in DepthSource.cs for AR Foundation? Are there any examples how to adapt the depth api for AR Foundation?

**Comment by ruofeidu** [comment]
Sorry but we don't own the code of ARFoundation but it is possible to tweak the code to make DepthLab compatible with ARFoundation. Or can we use ARFoundation and ARCore SDK at the same time? I am not very familiar with ARFoundation.

**Comment by ericloureiro** [comment]
> ...Or can we use ARFoundation and ARCore SDK at the same time?.

Short answer:  No.
We can not use both at the same time in Unity. Can not pass **EnsureGoogleARCoreIsNotPresent()** validation:
`
Error building Player: BuildFailedException: GoogleARCore detected. Google's "ARCore SDK for Unity" and Unity's "ARCore XR Plugin" package cannot be used together. If you have already removed GoogleARCore, you may need to restart the Editor.
`

I'm having a problem similar to the OP, but in my case, I want to use Occlusion Transparency from Depth Lab as it is not provided by [Occlusion Subsytem](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/manual/occlusion-subsystem.html) from AR Foundation.

In general, I too want to use ARCore Depth API in an AR Foundation project. Is there a way to adapt the scripts?
Being trying to tweak here and there on the API code but without so much luck.

**Comment by ruofeidu** [comment]
We recently released new updates using AR Foundation: https://github.com/googlesamples/arcore-depth-lab/releases please feel free to check it out :)
