### ISSUE TITLE
Noisy Point Cloud 

### ISSUE THREAD

**Issue by alexmanni** [googlesamples/arcore-depth-lab#21]
Hi,
I tried the point cloud sample and I noticed "flying points" when there are depth discontinuities in the scene, for example if I want to visualize the point cloud of a chair in a room there will be points flying in the air behind the chair besides the ones correctly visualized. As you know this is a common problem with ToF sensors where you can adjust a confidence threshold in order to minimize the anomalies.
I tried the sample with a Samsung Galaxy S8 and with a Samsung Galaxy S20+ that has its own ToF camera with VGA resolution, they have the same problem:
https://www.youtube.com/watch?v=YlbYWrjLWAQ

Is there a way to access the confidence of the DepthSource?

**Comment by ruofeidu** [comment]
Thank you Alessandro for your interests in DepthLab.

The smooth depth is post processed to cover the entire field of view of the camera. Thank you for your suggestions in confidence threshold, but it is not publicly available to access confidence now.

Would you like to share want you would like to achieve with filtering the point clouds? Maybe it's doable with smooth depth and a bit of processing around edges?

**Comment by alexmanni** [comment]
Thank you for the quick answer! 
Basically I would like to create a 3D bounding box without deep learning stuff, If I had a good point cloud I could take points at a certain height, for example a table surface, and draw a bounding box from there to the floor. 

For example here I can do that because the surface has no object on it and K-means clustering work, but on a table with objects this is not doable.
https://www.youtube.com/watch?v=Z0VRt50vNCE

**Comment by ruofeidu** [comment]
For simple scenes, a simple floodfill shall work with thresholding world-space heights. K-means may enforce the points to be separated into K clusters. I tried to segment out surfaces by touch and it works well, though that part of code is not opensourced (yet).

You may also take a look at SemanticPaint https://www.robots.ox.ac.uk/~tvg/projects/SemanticPaint/index.php.

I think it's still an open challenge for complex scenes without learning priors.

**Comment by alexmanni** [comment]
Thank you very much for the suggestions, I will check them out!

**Comment by ruofeidu** [comment]
We recently released new updates to the point cloud scene using more accurate raw depth API, please check it out: https://github.com/googlesamples/arcore-depth-lab/releases

**Comment by alexmanni** [comment]
Thank you very much! Awesome. Unfortunately, a paper using an earlier version of Depth Lab is already under review 😅. In order to remove flying points I applied a sort of canny edge algorithm to the depth map. Anyway, the new point cloud sample works well on Samsung galaxy S8. On the samsung galaxy s20+ is not very stable (gray screen, too many points to process?)
