### ISSUE TITLE
Unreal engine

### ISSUE THREAD

**Issue by fromEON** [googlesamples/arcore-depth-lab#23]
What about for Unreal engine?
It's been long time to support for Unreal engine with many features missing?

Is it deprecated for UE4? Or planning to release for UE5 with Depth API support?

**Comment by ruofeidu** [comment]
Sorry but this is beyond the scope of this project, which is targeted at Unity. However, the main point is to deliver the algorithms and ideas, which could be easily reproduced in Unreal Engine. See https://developers.google.com/ar/develop/unreal/quickstart for more details about Unreal + ARCore, but I am not familiar with it.
