### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by sergiosolorzano** [googlesamples/arcore-depth-lab#24]
Hello,
Can't build on Unity 2018.4.19f1 android 11 on win10. Getting error
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\2018.4.29f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "C:\Program Files\Android\gradle-5.6.4\lib\gradle-launcher-5.6.4.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleDebug"

stderr[

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\dirs\arcore-depth-lab\Temp\gradleOut\build.gradle' line: 136

* What went wrong:
Could not compile build file 'E:\dirs\arcore-depth-lab\Temp\gradleOut\build.gradle'.
> startup failed:
  build file 'E:\dirs\arcore-depth-lab\Temp\gradleOut\build.gradle': 136: expecting '}', found '' @ line 136, column 1.
  1 error

**Comment by ruofeidu** [comment]
Thank you for your interests for DepthLab!

Please follow https://developers.google.com/ar/develop/unity/android-11-build to configure the gradle. I could build it under your configuration following the instruction :)

**Comment by sergiosolorzano** [comment]
Thank you @ruofeidu.

I started with a fresh project and got it to build for 2018.4.19f1  :) 

I read here Unity 2018.4 I should use gradle version 5.1.1 https://docs.unity3d.com/Manual/android-gradle-overview.html . However the guide you kindly shared https://developers.google.com/ar/develop/unity/android-11-build says Unity 2018.4 or later, the <queries> element requires Gradle version 5.6.4 or later. What gradle version should I use?

Thanks a lot

**Comment by ruofeidu** [comment]
I used a Gradle version 5.6.4 and the latest gradle and both works. I also used Unity 2021.1 and it worked.
