### ISSUE TITLE
App opens on Pixel 2 XL but does not run AR - Google Play Services for AR Required

### ISSUE THREAD

**Issue by sergiosolorzano** [googlesamples/arcore-depth-lab#25]
Hello all

I'm on  2018.4.19f1 and a pixel 2 XL Android 11 and the build installed on the smartphone does not run the AR experience. 

I have Google Play Services for AR installed and updated.

I can see the sprites to choose the AR experience but the rest of the screen is black. I build & run a single scene and when the app opens I get "this application requires th latest version of google play services for AR", however I have Play Services for AR installed and updated.

If I build all scenes with the caroussel I get the same message that I required Play Services for AR and after pressing ok it shows me the Play Services for AR app to install but there is nothing to do because it's already installed. So next I go back to the app I built that is open and it says "depth api is not supported on this device. Please make sure your device is compatible". 

Pixel 2 XL is indeed an AR [enabled](https://developers.google.com/ar/discover/supported-devices) device.

Furthermore, I can confirm I can run AR on this phone with [Unity's AR Foundation](https://blogs.unity3d.com/2020/06/25/blend-virtual-content-and-the-real-world-with-unitys-ar-foundation-now-supporting-the-arcore-depth-api/) and the [ARCore Depth Lab example on the play store](https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab)

I did a factory reset on the phone but I still get this behaviour.

I thought it may be a problem with the arcore-unity-sdk version but in trying to upgrade from arcore-unity-sdk-1.18 to 1.21 I get gradle errors and can't build.

Anyone else experiencing this? Any guidance really appreciated please

**Comment by sergiosolorzano** [comment]
I did a fresh installed with [sdk 1.21](https://github.com/google-ar/arcore-unity-sdk) on Unity 2020.2 and works great :) 

What is the difference in terms of arcore depth functionality between this and the project with [arcore sdk](https://github.com/google-ar/arcore-unity-sdk)? I'm trying to work out if I move on with sdk 1.21 not using depth lab project or what depth functionality i'm leaving behind?

**Comment by ruofeidu** [comment]
We released two new updates to this project using AR Foundation and ARCore Unity SDK respectively, please check out if these fit your needs: https://github.com/googlesamples/arcore-depth-lab/releases
