### ISSUE TITLE
Is the deep solving algorithm open source

### ISSUE THREAD

**Issue by wangguangyuan** [googlesamples/arcore-depth-lab#27]
Thanks for the excellent work of open source，
For whether the algorithm for deep solving in the project is open source, look at the relevant code in that file。

**Comment by ruofeidu** [comment]
I think you are mentioning about the depth estimation algorithm here? It's not opensourced in this project but you may refer to this paper for more detail: https://research.google/pubs/pub48288/ :)

**Comment by ruofeidu** [comment]
I am going to close the ticket, but please specify which part of algorithm you are looking into. The opensourced algorithms in this repo is available at: https://augmentedperception.github.io/depthlab/
