### ISSUE TITLE
URP?

### ISSUE THREAD

**Issue by mohsen123** [googlesamples/arcore-depth-lab#28]
Isn't it supporting URP?

**Comment by tcdat96** [comment]
I'm trying URP but it doesn't seem to work. Did you figure it out?

**Comment by mohsen123** [comment]
> I'm trying URP but it doesn't seem to work. Did you figure it out?
Not Yet! seems some shaders need some changes.

**Comment by ruofeidu** [comment]
Sorry but I haven't used URP so far. May I ask which scenes would you like to transfer to URP? Avatar locomotion or object placement?

**Comment by mohsen123** [comment]
> Sorry but I haven't used URP so far. May I ask which scenes would you like to transfer to URP? Avatar locomotion or object placement?

My target is point cload one, but I tried many Examples, UI, even the Target, is working fine but no Camera appears in the bg [black screen], maybe there is an issue with ARBackground shader,

**Comment by ruofeidu** [comment]
We have a new Point Cloud scene using raw Depth API now using both AR Foundation and ARCore Unity SDK. Please feel free to check it out: https://github.com/googlesamples/arcore-depth-lab/releases

**Comment by pinklover91** [comment]
Hi I'm trying to build the arcore-unity-sdk branch using URP, however, I keep getting black screen for my camera, because we don't have ARBackgroundRendererFeature in ARCore. Does anyone encounter this issue before? Do you have any workaround to get this work?

**Comment by ruofeidu** [comment]
Hi pinklover91, would you like to ensure your Unity version is Unity 2019.4.*? Sorry but I haven't got bandwidth to try the latest Unity versions, but it works well on my Windows, Mac, and Linux.

**Comment by ruofeidu** [comment]
BTW, you need to "Download and import arcore-unity-sdk-1.24.0.unitypackage or newer into the sample project. " See the README.md in that branch.

**Comment by pinklover91** [comment]
> Hi pinklover91, would you like to ensure your Unity version is Unity 2019.4.*? Sorry but I haven't got bandwidth to try the latest Unity versions, but it works well on my Windows, Mac, and Linux.

Hi yes, I'm using 2019.4.25f1.

**Comment by ruofeidu** [comment]
BTW, you need to "Download and import arcore-unity-sdk-1.24.0.unitypackage or newer into the sample project. " See the README.md in that branch.

Did you do this as well?

**Comment by pinklover91** [comment]
> BTW, you need to "Download and import arcore-unity-sdk-1.24.0.unitypackage or newer into the sample project. " See the README.md in that branch.
> 
> Did you do this as well?

Hi Ruofeidu, thank you so much for your hard work, taking your time replying and testing as well. I really appreciate it.
Yes, I did this as well. Using both 1.25.0 and 1.24.0 versions.
Still encountering black screen using URP, only when I remove my URP package, then I will be able to see my camera feed. 
May I know if there's any particular setting similar to ARBackgroundRendererFeature settings in URP like AR Foundation? Or another alternatives workaround to solve this issue?

**Comment by ruofeidu** [comment]
Hi pinklower91,

I recently updated the app in Play Store and build it with Unity 2019.4.36f and I can verify it's working. Unity 2019.4.37f has some bugs in collision scene. But let me know if you are still encountering this bug.

Best,
Ruofei
