### ISSUE TITLE
Device compatibility

### ISSUE THREAD

**Issue by Iansi6** [googlesamples/arcore-depth-lab#3]
All ARCore compatible devices are compatible with this API? I have a Samsung Galaxy S8 and S9.

**Comment by kidavid** [comment]
Please find the list of ARCore compatible devices with Depth API support here: https://developers.google.com/ar/discover/supported-devices

Please look for "Supports Depth API" in the **Notes** column of each listed device.

**Comment by yearofthewhopper** [comment]
Hi! So, I know this repo is set up to only work with android but i feel it should be a little more explicit that ARcore's depth api only works with android devices. On the above link: for example under the section of supported devices it says 

> iOS
> ARCore supports all ARKit-compatible devices running iOS 11.0 or later.
> 
> Verification of newer devices:
> 
> Newer devices are added to the list of devices (below) after they have been verified.
> 
> Support for older devices:
> 
> Support for specific features depends on the ARCore feature and the version of the device, as follows:
> 
> Cloud Anchors: Cloud Anchors are not supported on iOS devices that are older than the devices in the following list.
> 
> Augmented Faces: Augmented Faces may work on iOS devices that are older than the devices in the following list, but may not operate at the required frame rates for live AR use cases.
> 
> The following iOS devices have been verified to work with **all ARCore** supported features:

The "all ARCore" section of this is very misleading since presumably all ARCore features includes the Depth API. I've also seen several [articles](https://www.infoq.com/news/2019/12/android-arcore-depth-api/) that also reference that Depth API can be used with many models of iphones. When I did manage to get these examples to compile for iOS--I was given a prompt that linked me to the above compatibility site. 

So, I'm trying to close the loop on potential confusion here and clarify: does the depth api work for iOS at all?

**Comment by kidavid** [comment]
Depth API is a specific feature of ARCore, which runs on a subset or ARCore-certified devices. At this point, iOS devices are not compatible.

**Comment by yearofthewhopper** [comment]
@kidavid Thank you! I appreciate this response!

**Comment by Zumbalamambo** [comment]
@kidavid very nice!... dont support ios.. they dont write any apps for android.. they just dont contribute to the opensource

**Comment by fredsa** [comment]
@yearofthewhopper Thank you for highlighting the confusion. We'll update the wording in the iOS section ("_The following iOS devices have been verified to work with all ARCore supported features:_") to be less confusing.

In case there are other improvements we should make:
- Would it help if we updated the `README.md` in this repo?
- In addition, is there anything you think we should do to the Unity project to make this clear when the project is first opened?
- Finally, anywhere in our developer docs (developers.google.com/ar/develop) where the device support aspect is not as clear as it should be?

**Comment by yearofthewhopper** [comment]
@fredsa Thank you for asking these follow up questions! 

updating the readme.md would be really helpful as I wouldn't have attempted to even use the depth api had I known it wasn't supported by iOS devices and hence would've saved me a lot of time and heartache. 

The unity project itself is set up to work on android platform; which I think makes sense given that it only works for android devices--but I still feel like a note in the project itself to only use with android devices would've been helpful (given that not every user is going to read the readme.md)

The linked website https://developers.google.com/ar/develop/unity doesn't seem to clarify anything in regards iOS and ARCore's Depth API, like [https://developers.google.com/ar/develop/unity/depth/overview](https://developers.google.com/ar/develop/unity/depth/overview) for example could say "not available for iOS". There's a lot of opportunities to say explicitly in the documentation that this "subsection of ARCore" doesn't work with iOS when all others do?

**Comment by fredsa** [comment]
Thanks again for the feedback.

We're putting together a few updates to at least these pages to help clarify Depth API support and available features when targeting iOS:
- https://developers.google.com/ar/discover/supported-devices
- https://developers.google.com/ar/develop/unity
- https://developers.google.com/ar/develop/unity/depth/overview


For the project itself we could add a compile time error, e.g.

```
#if !UNITY_ANDROID
   // Depth API support currently available on Android only.
   // https://developers.google.com/ar/discover/supported-devices
   #error Build platform must be set to Android.
#endif
```

**Comment by Thaina** [comment]
@fredsa Is the devices that not currently support depth api in that list could be possible to be supported in the future?

To be honest I have Nokia 7 plus and I want to know is it just waiting for calibration or it was tested and considered impossible. Also I prefer Nokia (Also Motorola) brand but it seem none of them currently support depth api. Do we have anything particular with Nokia and Motorola?

I wish you would also mark `impossible for depth api` so people could know they should just buy new device that support it if they want to play with depth api app and don't need to wait hopelessly

**Comment by fredsa** [comment]
@Thaina Our goal is to make the Depth API available on as many ARCore supported devices as possible. However, the additional depth processing requires additional CPU resources that always available on lower-end and older devices. While we do expect to expand the list of supported devices over time, it's unlikely that all currently ARCore supported devices will be able to support the Depth API. We do continuously look for improvements to ARCore's algorithms, to increase the number of supported devices and make additional CPU capacity available to app developers.

**Comment by fredsa** [comment]
The following docs have been updated:

- https://developers.google.com/ar/discover/supported-devices
- https://developers.google.com/ar/develop/unity
- https://developers.google.com/ar/develop/unity/depth/overview

**Comment by Thaina** [comment]
@fredsa I wish I could see the possibility on each one so I could decide (for me and some people I would suggest them) should wait or just find new device for support ARCore

Is Nokia 7 plus on the side of process or on the side of `too old and too low to be support with current algorithm` though?

If you need more than a year to support old device I think it then not worth to do. I would have buy new one for the next year. Nokia 7 plus already being degraded for everyone bought it since Q1 2018

**Comment by fredsa** [comment]
@Thaina Once we're confident that a device can be supported, we update the device profile and mark the device as supported. So, unfortunately there's not a way of knowing which devices will be able to be supported without doing the actual work to support them and verify.

**Comment by Thaina** [comment]
@fredsa I know, what I mean is, we should have a tag or some marker to tell that it was `not confident that a device can be supported` or `confident that a device cannot be supported`

In other word, which device was already tested but cannot support, and which is still in testing process (and which is not even begin to test yet)

**Comment by ruofeidu** [comment]
Thank you all for your feedback, we have added the supported device list in `README.md` as follows:

> ARCore Depth API is enabled on a subset of ARCore-certified Android devices. iOS devices (iPhone, iPad) are not supported. Find the list of devices with Depth API support (marked with Supports Depth API) here: https://developers.google.com/ar/discover/supported-devices. See the ARCore developer documentation for more information.

**Comment by Thaina** [comment]
Hello. Do we have any changes since the last update

Could we have information in that page as `json` file in github repo? So we could always see changes and changelog (and also diffing)

**Comment by CyberColtz21** [comment]
How do I enable the Occlusion feature on a Samsung S9? Whenever I use the app, it's the same experience as the older versions of ARcore like in 2018. I've been using that for about six years and whenever I use it, my hand is always behind the virtual objects. Do I need to edit the code myself, like open source or maybe not? I'm not too skilled in programming or code. This is all pretty new to me.

**Comment by ruofeidu** [comment]
> Hello. Do we have any changes since the last update
> 
> Could we have information in that page as `json` file in github repo? So we could always see changes and changelog (and also diffing)

Hi Thaina,

We haven't updated much since the last update. Please feel free to suggest things you'd like to have in the next version. The legacy arcore-sdk branch contains all the examples we opensourced for the ACM UIST 2020 paper while the AR Foundation version provides a minimal set of samples using AR Foundation SDK to implement depth. We haven't migrated all the samples from the paper to ARFoundation yet, but I'd like to merge pull requests from contributors.

**Comment by ruofeidu** [comment]
> How do I enable the Occlusion feature on a Samsung S9? Whenever I use the app, it's the same experience as the older versions of ARcore like in 2018. I've been using that for about six years and whenever I use it, my hand is always behind the virtual objects. Do I need to edit the code myself, like open source or maybe not? I'm not too skilled in programming or code. This is all pretty new to me.

Hi CyberColtz21, 

Occlusion and depth are supported as shown in https://developers.google.com/ar/devices. You can download our sample app from here https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab before playing with the code :) 

Cheers,
Ruofei

**Comment by Darkar25** [comment]
My Samsung Galaxy S8 is supported accoring to the link in readme, but its unsupported according to play store?thats strange...is there anything that can be done?

**Comment by CyberColtz21** [comment]
> > How do I enable the Occlusion feature on a Samsung S9? Whenever I use the app, it's the same experience as the older versions of ARcore like in 2018. I've been using that for about six years and whenever I use it, my hand is always behind the virtual objects. Do I need to edit the code myself, like open source or maybe not? I'm not too skilled in programming or code. This is all pretty new to me.
> 
> Hi CyberColtz21,
> 
> Occlusion and depth are supported as shown in https://developers.google.com/ar/devices. You can download our sample app from here https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab before playing with the code :)
> 
> Cheers, Ruofei

Your app supports my phone... But the occlusion does not. Isn't that the main point of this app? Why is this so confusing? It could have been programmed to include occlusion feature on galaxy S9 and still I've never experienced such a thing. I'd like it if you explained this better.
