### ISSUE TITLE
PointCloud not getting updated each frame

### ISSUE THREAD

**Issue by nikhilsawlani** [googlesamples/arcore-depth-lab#30]
Hi, I was trying to build an application using the RawPointCloud Scene, I want to save the point cloud generated inside a .ply file, while I was able to create a sample PLY which can be found [here](https://drive.google.com/file/d/1XXwIa7erNwAnuL2kiL6Qh5ssVoUJJpOw/view?usp=sharing), what I noticed each frame is producing new point clouds not updating last points if users haven't moved.

So in my ply file, I can see layers of points with slightly different positions in world space, so are the depth points tracked across frames through some identifiers?

for creating .ply I'm creating a list that saves vertices and their color in a session and saves them as .ply

`if(vertex != Vector3.zero)
{
      updatedPoints.Add(vertex);
      updatedColors.Add(color);
 }`

**Comment by ruofeidu** [comment]
Hi Nikhil,

Thank you for your interests in Depth Lab and thanks for sharing the PLY file!

Have you tried filtering by confidence level? I would suggest using 0.5 or higher as the confidence threshold.

Note that the depth map is pretty dense without filtering by confidence. In addition, the individual points are not tracked, but the data is being updated, resulting in closer point to be duplicated in close positions. To have better accuracy, you may use anchors for each of the frames added to the PLY. A Java example can be found at: https://github.com/google-ar/arcore-android-sdk/blob/master/samples/raw_depth_java/app/src/main/java/com/google/ar/core/examples/java/rawdepth/DepthData.java#L53. Another idea is to use Octrees and nearest neighbor search to better fuse them.

**Comment by nikhilsawlani** [comment]
Hi @ruofeidu,

Thanks for the response, I tried changing the confidence level to up to even 1.0 and added Anchors to Camera poses in Unity, but still I can see up to 7-8 duplication for the same point in space.
I will try Octrees and nearest neighbor search to fuse them any example you can refer will be helpful though.

Another question (a little different) is there any way to export the Raw Depth Mesh created in Unity during Runtime? as I see creating a Mesh already fuse points so we don't have to do on .ply files.

**Comment by ruofeidu** [comment]
I implemented exporting point to PLY in Unity before, but not in Depth Lab. Runtime writing may be challenging while a better approach may be cache in memory and then export to PLY.  I know there is an app of live scanner https://youtu.be/EerbBxLt7hI?t=48 that leveraged our raw Depth API for your reference.
