### ISSUE TITLE
No Shadows in Collision Scene

### ISSUE THREAD

**Issue by knewk** [googlesamples/arcore-depth-lab#38]
Nice work.  I'm trying to get shadows from the throw objects in the Collision scene but they seem to be missing.  They are there in the non AR Foundation version. Looks like the shadow receiving mesh is obscured by the AR Foundation occlusion.

**Comment by ruofeidu** [comment]
Yes, thank you Martin for pointing out. DepthLab was originally developed for ARCore legacy SDK while we haven't integrated the shadow receiver to ARF. Please feel free to contribute :)

**Comment by knewk** [comment]
I did some work converting a while back.  Have a look at this. [https://youtu.be/35ji2r2RCYQ](url)

**Comment by ruofeidu** [comment]
This is really cool! Please feel free to send over a PR.

**Comment by knewk** [comment]
Sorry, what's a PR?  You can contact me via the https://knewk.com/contact-us/ and I'll give you my email etc.

**Comment by ruofeidu** [comment]
Sorry for my abbreviation - PR is short for pull request. It's your choice whether or not to contribute to the codebase. I probably won't have cycles to transfer all scenes from legacy SDK to the ARF one but will try my best - and I welcome contributions :)

**Comment by knewk** [comment]
Hi All,  got the shadows working in the collision scene.  Was as simple as turning on the Shadow Type to Hard Shadows for LightEstimation prefab.  Setting the shadow quality setting in Project Settings to high.  And the Shadow Distance to 6 and Shadow Near Plane Offset to 0.1.

**Comment by ruofeidu** [comment]
Hi knewk, thanks a lot for sharing! Would you like to create a pull request and patch the code?

**Comment by knewk** [comment]
> Hi knewk, thanks a lot for sharing! Would you like to create a pull request and patch the code?

Cheers. Can do.  I look at some other changes I'd like to make and also discuss stuff. e.g. Upgrading to latest 2020 Unity and 1.29 AR Core Extensions. What's the best way to communicate with contributors?

**Comment by knewk** [comment]
The shadow is there however it seems to be too big.  Maybe the shadow receiver mesh is too close.  This could also explain why it shows up in front of the AR Foundation occlusion. I need to investigate further.  Below is a screen shot of the current shadow using my suggestions above, moving on a frame where a shadow is cast and received by an object showing a comparable size, and my shadow receiver implementation incorporating `occlusionManager.TryAcquireEnvironmentDepthCpuImage(out XRCpuImage cpuDepthImage) ` into DepthSource.

![Screenshot 2022-02-27 200833](https://user-images.githubusercontent.com/15896950/155878423-cdf1e23d-f178-4588-a98d-46000983423b.png)

**Comment by ruofeidu** [comment]
Hi Akssieg,

The shadow is in legacy ARCore SDK branch and we don't have enough bandwidth to port it to the ARF version. 

I always welcome PRs and please feel free to contribute your shadow!!

Cheers,
Ruofei
