### ISSUE TITLE
Whether DepthSource.cs can use with Arkit in ios?

### ISSUE THREAD

**Issue by ThmCuong** [googlesamples/arcore-depth-lab#39]
I am interested in this project very much and want to use it in my app. Whether DepthSource.cs can use with Arkit in ios?

**Comment by ruofeidu** [comment]
Hi ThmCuong,

I haven't used ARKit so far, but frankly speaking, DepthLab is designed with an input of depth map, so you should be able to change the depth API from ARCore to ARKit. And I would love to accept pull requqests for anyone who has done this :) 

Cheers,
Ruofei

**Comment by knewk** [comment]
Hi,  I'm interested in doing the same thing.  I understand that AR Foundation doesn't support the iPhone forward facing depth camera only the Lidar.  Here is some discussion/code to expose the iPhone depth camera.  I'm going to be seeing if this works.  Will let you know how things go. Once you have the depth image DepthSource.cs can expose the compute shader generated surface on the iPhone.
[https://github.com/Unity-Technologies/arfoundation-samples/issues/615](url)

**Comment by ruofeidu** [comment]
Thank you knewk! I honestly never programmed depth in iOS.

Hopefully this issue can help future developers!
