### ISSUE TITLE
Is it possible to play recorded ARSessions in the Unity Editor or on an emulator?

### ISSUE THREAD

**Issue by drskort** [googlesamples/arcore-depth-lab#40]
Hello, first of all really great work on the arcore-depth-lab!

I was wondering whether it is possible to play recorded ARSessions with the ARPlaybackManager in the Unity Editor or on an android emulator. This would allow people to iterate faster when developing AR applications using ARFoundation.
When trying to test our application in an android studio emulator, the camera didn't show us anything in our application despite being set to a virtual scene. It did work in the camera app.
In case this feature doesn't work in both an emulator and the editor, will this be a planned feature?
Thank you in advance!

Rodion

**Comment by ruofeidu** [comment]
Thank you Rodion for the feature request! 

I'll talk with my colleagues to answer this question.

P.S., when I was prototyping, I was using my own testbed with depth extracted with a dynamic virtual scene; I do agree playing back in Unity will great accelerate the iterations :)
