### ISSUE TITLE
Collision Scene: Projectile Anchoring causes Object to Appear Next to Camera

### ISSUE THREAD

**Issue by knewk** [googlesamples/arcore-depth-lab#41]
Happens on rare occasions.  Have found it in my other uses of the depth lab framework.  When the projectile stops moving the Projectile script creates and Anchor for the object.  This teleports the object to next to the camera.  I assume to 0,0,0. 
![Screenshot_20220227-120233](https://user-images.githubusercontent.com/15896950/155864171-6379b5db-612a-4615-b448-a472748ff294.png)

**Comment by ruofeidu** [comment]
Thank you knewk for reporting! From my personal perspective, the Play Store version and the ARCore legacy SDK version is more stable than the current master branch (ARF) and I don't know why.
