### ISSUE TITLE
using custom deep learning depth models?

### ISSUE THREAD

**Issue by FYtrace** [googlesamples/arcore-depth-lab#43]
Hi, thanks for your wonderful work. Does this project support custom depth models (replace ARCore depth map) based on deep learning as input?

**Comment by ruofeidu** [comment]
You may implement your own depth source, the MotionStereoDepthSource is just one implementation. Check out https://storage.googleapis.com/tfjs-models/demos/3dphoto/index.html for a recent 3D demo using ML portrait depth and DepthLab 3D photo scene.
