### ISSUE TITLE
Depth in WebCam on Web Browser

### ISSUE THREAD

**Issue by kavikode** [googlesamples/arcore-depth-lab#44]
Great work with the project!

We would like to apply real time 3D AR interactions with the video stream from a WebCam in a browser.

Is this package available on JavaScript? It would greatly improve accessibility.

I was unable to find the 3D portrait that only works on humans. We are looking for the entire 3D surface so that we can create our robotic interface.

Many thanks!

**Comment by ruofeidu** [comment]
If you try out the "AR Depth Sensing" demos on this page they seem to work correctly: https://storage.googleapis.com/chromium-webxr-test/r991081/proposals/index.html

Then you may combine this with three.js and translate our C# code in the arcore-unity-sdk branch into JavaScript.

Cheers,
Ruofei
