### ISSUE TITLE
Linking ToF Depth data with main camera's image.

### ISSUE THREAD

**Issue by johnnokomis** [googlesamples/arcore-depth-lab#45]
For doing turntable photogrammetry I'm wondering if there's an easy way to save the depth map from my LG V60's ToF sensor along with the RAW pic from my main camera.  There's a way to sorta do it with an annoying workaround.. taking the photo using portrait mode then extracting the depth map from the meta data. This however is very time consuming but also you lose all control of the cameras manual settings. I'm taking the dataset back to Metashape on my PC so all the hardware intensive computing will be done on that machine. I cant believe how this simple task of tagging depth information beside a photo is so far impossible to do. How did that dumb fruit company implement ToF/Lidar hardware so much better than Android? Like, its not even close. Embarrassing.

**Comment by ruofeidu** [comment]
Hi johnnokomis,

I can get ToF depth from an advanced Samsung / Huawei phone. We have a Recorder.cs in this repo but it saves the entire ARCore session. Maybe save the depth map CPU data in a buffer while recording, then write the buffer to disk after recording stops?

Cheers,
Ruofei

**Comment by ruofeidu** [comment]
Let me know if you have further questions, I'm closing it for now as I got no responses :)

**Comment by johnnokomis** [comment]
That's fine I understand, I believe it's impossible what I'm trying to achieve. What a bummer too. It's no wonder Samsung dropped their ToF sensors in their flagships. It's such an amazing piece of tech but so far it's been implemented so poorly. 3D scanning is almost an Apple exclusive with how well they've adopted Lidar. While there are a few 3D scanning apps on Android.. their iPhone counterparts offer far more in app features that increase the quality of the output. I'm Android until the end but I sadly have to hand Apple the victory here 😔
