### ISSUE TITLE
can run sample app on Mac silicon? 

### ISSUE THREAD

**Issue by kotran88** [googlesamples/arcore-depth-lab#46]
Hello I run sample app with 2020.3.29f1 / 2021.3.0f1(Mac silicon) 
and causing error 

Assets/ARRealismDemos/Common/Scripts/Recorder.cs(24,7): error CS0246: The type or namespace name 'Google' could not be found (are you missing a using directive or an assembly reference?)

Assets/ARRealismDemos/Common/Scripts/Recorder.cs(38,12): error CS0246: The type or namespace name 'ARCoreExtensions' could not be found (are you missing a using directive or an assembly reference?)

Assets/ARRealismDemos/Common/Scripts/Recorder.cs(40,13): error CS0246: The type or namespace name 'ARRecordingManager' could not be found (are you missing a using directive or an assembly reference?)

what maybe the problem?

**Comment by ruofeidu** [comment]
Hi kotran88,

I tested both Mac and Windows.

It seems that you did not have AR Foundation or ARCore SDK correctly set up.
Which branch are you using?

There are Getting started section that you need to follow in README.md

Cheers,
Ruofei
