### ISSUE TITLE
Creating pointcloud

### ISSUE THREAD

**Issue by Zumbalamambo** [googlesamples/arcore-depth-lab#5]
How can I create a point cloud of the environment using depth api?

**Comment by kidavid** [comment]
You can create an empty **GameObject** and add a **MeshFilter** and a **MeshRenderer** component. Finally, add our **PointCloudGenerator.cs** component, then call its "void ComputePointCloud()" method to update the point cloud.

https://github.com/googlesamples/arcore-depth-lab/blob/master/Assets/ARRealismDemos/Common/Scripts/PointClouds/PointCloudGenerator.cs

**Comment by ruofeidu** [comment]
Please also check out the latest release: https://github.com/googlesamples/arcore-depth-lab/releases and the Play Store app for fusing raw point clouds: https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab
