### ISSUE TITLE
Depth API not supported: OnePlus 11

### ISSUE THREAD

**Issue by rl27** [googlesamples/arcore-depth-lab#50]
I'm using a OnePlus 11 and I installed this app from the Google Play Store. Upon opening the app, I get the warning: "Depth API is not supported on this device. Please make sure your device is compatible."
However, OnePlus 11 is listed as supporting the Depth API: https://developers.google.com/ar/devices
What could be causing this issue?

**Comment by ruofeidu** [comment]
Thank you rl27! I'll raise it to the team.

Would you confirm that your phone is OnePlus 11 5G? Thank you!

**Comment by rl27** [comment]
Yes, it's a OnePlus 11 5G. Thank you for the prompt reply!

**Comment by devbridie** [comment]
Could you please post the output of `adb shell getprop ro.build.fingerprint` using the affected device?

**Comment by rl27** [comment]
OnePlus/CPH2451/OP594DL1:13/TP1A.220905.001/T.R4T3.110730f_335df-2:user/release-keys

**Comment by rl27** [comment]
Hi! Is there any update on getting the Depth API working with my OnePlus 11?

**Comment by ruofeidu** [comment]
Hi I saw the team has created a ticket for you and it is likely to be fixed in the next ARCore patch. Thanks for reporting!
