### ISSUE TITLE
Problem with updated packages

### ISSUE THREAD

**Issue by ODeviatkin** [googlesamples/arcore-depth-lab#51]
I faced difficulties assembling this project as per the provided instructions. The suggested versions of Unity (2020.3.6f1), AR Foundation (4.2.0-pre.7), and ARCore Extensions (1.24) didn't work for me. I had to use the latest available versions to make it functional: Unity (2023.1.0b20), AR Foundation (5.0.6), and ARCore Extensions (1.38.0).

Unfortunately, I encountered some issues with this updated configuration. In comparison to the Google Play version of project, objects tend to partly fall through surfaces and behave worse in my assembly. Overall, the project's performance is considerably worse, than Google Play version of project on the same device.

Given the nature of library updates, I understand that such discrepancies are expected. However, being new to this technology, I'm curious to know which specific aspect is causing the most difficulties.

I haven't made any changes to the code. The issues arose solely from updating the libraries, which were necessary for the project to function.
![image](https://github.com/googlesamples/arcore-depth-lab/assets/74683207/23fea2f0-b7c7-4a7e-9c0b-e63b0f13c3bc)

If it's necessary, I can provide all information about fail in build with requirements in readme.

**Comment by ruofeidu** [comment]
Hi Aleksander,

I recently successfully compiled both main branch and the more comprehensive arcore_unity_sdk branch using Unity2022.2.2f1 with ARCore Extensions (https://github.com/google-ar/arcore-unity-extensions/releases the last one, 1.38.0). Frankly speaking, I haven't been maintaining this project after 2021 - all the code and shaders are still useful in my future projects - and I really don't have time to investigate why Unity version updates keep breaking things -_-b if you have time to figure that out, I am more than happy to accept a pull request / branching.


Cheers,
Ruofei
