### ISSUE TITLE
Can't find other samples

### ISSUE THREAD

**Issue by TimmyBest** [googlesamples/arcore-depth-lab#54]
In the new version we can't find the Midas and splat and laser. Where did they go?
The other branch from 2 years ago has them but it is completely broken and does not compile.

**Comment by ruofeidu** [comment]
Hi TimmyBest,

Please refer to https://github.com/googlesamples/arcore-depth-lab/tree/arcore_unity_sdk for the old algorithms and SDKs.
Apologies that I didn't have time to catch up with the ever-changing Unity & ARCore APIs but I welcome all contributions from the community to migrate old algorithms to the latest branch.

**Comment by TimmyBest** [comment]
Sure we can refer to the stale branch but it doesn't even compile :(

**Comment by ruofeidu** [comment]
It does compile :) I even tried it late last year, just follow the README.md and use the exact Unity version :)

**Comment by ruofeidu** [comment]
Let me know if you have further issues, ow, I'll close it.
