### ISSUE TITLE
how to use Screen position get the accurate depth value ?

### ISSUE THREAD

**Issue by ZFHung** [googlesamples/arcore-depth-lab#55]
this is my code 

void Arrow3DMarker()
    {
        if (Input.touchCount > 0)
        {
            Touch touch = Input.GetTouch(0);
            // only count touches that just began
            if (touch.phase == TouchPhase.Began)
            {
                var screenPosition = touch.position;
                if (_depthImage.HasValue && screenPosition != null)
                {
                    var uv = new Vector2(screenPosition.x / Screen.width, screenPosition.y / Screen.height);
                    //var uv = new Vector2(0.5f,0.5f);
                    var DepthDistance = ComputeCenterScreenDistance(uv);
                    Quaternion? orientation = ComputeCenterScreenOrientation(uv);
                    if (DepthDistance > 0 && orientation != null)
                    {
                        Vector3 translation = _camera.ScreenToWorldPoint(new Vector3(
                                                Screen.width * uv.x,
                                                Screen.height * uv.y,
                                                DepthDistance));
                        //var worldPosition = _camera.ScreenToWorldPoint(new Vector3(screenPosition.x, screenPosition.y, DepthDistance));
                        GameObject ArrowMarker= Instantiate(_prefabToSpawn, translation, orientation.Value);
                    }
                }
            }
        }
    }

**Comment by ruofeidu** [comment]
Refer to this line here: 
https://github.com/googlesamples/arcore-depth-lab/blob/master/Assets/ARRealismDemos/OrientedReticle/Scripts/OrientedReticle.cs#L87C30-L87C57
