### ISSUE TITLE
Unity version not mentioned; changes required for 2019.4 LTS support

### ISSUE THREAD

**Issue by hybridherbst** [googlesamples/arcore-depth-lab#6]
Current Unity version is 2018.4 LTS.

For 2019.4 LTS, the following packages need to be added:
- com.unity.xr.legacyinputhelpers
- com.unity.multiplayer-hlapi

**Comment by kidavid** [comment]
Thank you for the tip, @hybridherbst !
We will consider this change in our next update.

**Comment by hybridherbst** [comment]
Thanks!
One note: common usage of GitHub would be to leave Issues open until they are fixed to avoid other people reporting the same issues... This also allows other users to see issues that are still open when they try to get something to work.

**Comment by ruofeidu** [comment]
Thank you @hybridherbst for your feedback. We have added the following pointers to README.md.

> These samples target Unity 2018.4.16f1 and require ARCore SDK for Unity v1.18.0 or newer.

**Comment by hybridherbst** [comment]
I think the point of this issue here was to also help other people use it on 2019.4. Why not add the information as well - you can point out that only 2018 is officially supported if that's the concern here.
I can tell you that it works fine on 2019 though :)
