### ISSUE TITLE
Broken Link on Play Store for Depth Lab

### ISSUE THREAD

**Issue by hybridherbst** [googlesamples/arcore-depth-lab#7]
On the [Play Store page](https://play.google.com/store/apps/details?id=com.google.ar.unity.arcore_depth_lab), the description has broken links:
![image](https://user-images.githubusercontent.com/2693840/85849095-9e841100-b7aa-11ea-9b88-1293315c1012.png)

These two both point to 
https://developers.devsite.corp.google.com/ar/depth
which in turn brings me to what looks like an internal login page that didn't get a design overhaul in a couple of decades :)

![image](https://user-images.githubusercontent.com/2693840/85849191-cc695580-b7aa-11ea-828d-b43cd7d3555f.png)

**Comment by kidavid** [comment]
Thank you for bringing this to our attention, @hybridherbst !
We will update the listing with the following URL: https://developers.google.com/ar/
