### ISSUE TITLE
Why exclude the Packages directory?

### ISSUE THREAD

**Issue by andybak** [googlesamples/arcore-depth-lab#8]
It makes this much more fragile and prone to breakage. The whole point of putting an entire Unity project in a repo is to have a reliable, reproducible set up. The vast majority of Unity projects on Github include Assets, Packages and ProjectSettings and in my experience the ones that don't are much less likely to work without some fixes at my side.

**Comment by ruofeidu** [comment]
For now, we would like to point users to integrate the Unity package at https://github.com/google-ar/arcore-unity-sdk/releases. Sorry for the inconvenience.
