### ISSUE TITLE
Create a simple working demo

### ISSUE THREAD

**Issue by giansimo** [googlesamples/arcore-depth-lab#9]
Hi everybody, 
I'm having some problems with creating a simple working demo from 0.
My goal is to put some GameObject in the scene with a custom material and use the Depth map to occlude part of the cube when it's not visible. Which are the steps to get it?

- Add prefabs for the camera (ARcore Device) and for illumination (Environmental Light).

- Enable Depth Mode in the session config attached to the ARcore Device.

- Add DepthSource component to the ARcore Device.

- Add some Cubes with the DepthTarget component attached.

When I run, no depth info is used and cubes appear in the old way.
What's is my fault?

**Comment by ruofeidu** [comment]
Hi giansimo,

Please let me know if you still need help. ARCore preview mode does not support depth API yet so we need to deploy the app onto the actual devices for testing.
